[package]
name = "mopm"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
hex = "0.4.3"
nix = { version = "0.29.0", features = ["user"] }
num_enum = "0.7.2"
rpassword = "7.3.1"
sha2 = "0.10.8"
term = "0.7.0"
thiserror = "1.0.61"
